config:
  credentials: []
  project_repos:
    code-repo.d4science.org/MaDgIK/uoa-repository-manager-service:
      branch: master
      repo: https://code-repo.d4science.org/MaDgIK/uoa-repository-manager-service.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-service git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-rust-lobster.sh
        container: qc.acc_muggy-cinnamon-hornet
  QC.Doc:
    repos:
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-service find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-sangria-lizard.sh
        container: qc.doc_seedy-saffron-nightingale
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-service git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-seashell-forest.sh
        container: qc.doc_wiggy-yellow-dragon
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-service markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-ultramarine-squid.sh
        container: qc.doc_thirsty-russet-dolphin
  QC.Lic:
    repos:
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-service licensee:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-wisteria-clam.sh
        container: qc.lic_hilly-amaranth-dog
  QC.Sty:
    repos:
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-service checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-gold-bee.sh
        container: qc.sty_snoopy-fuchsia-cat
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-service hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-smalt-zebra.sh
        container: qc.sty_snippy-russet-uguisu
  QC.Ver:
    repos:
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-service get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-cinnamon-squirt.sh
        container: qc.ver_flimsy-harlequin-caiman
timeout: 5400
