config:
  credentials: []
  project_repos:
    code-repo.d4science.org/MaDgIK/uoa-repository-manager-service:
      branch: master
      repo: https://code-repo.d4science.org/MaDgIK/uoa-repository-manager-service.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-service git:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-seashell-otter.sh
        container: qc.acc_snippy-tangerine-crocodile
  QC.Doc:
    repos:
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-service find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-purple-stingray.sh
        container: qc.doc_snoopy-azure-mist
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-service git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-alizarin-gar.sh
        container: qc.doc_muzzy-sepia-walrus
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-service markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-magnolia-nightingale.sh
        container: qc.doc_thirsty-cornflower-molly
  QC.Lic:
    repos:
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-service licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-mauve-chinchilla.sh
        container: qc.lic_woolly-zucchini-goose
  QC.Sty:
    repos:
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-service checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.silly-pink-beetle.sh
        container: qc.sty_snippy-wisteria-moth
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-service hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-sapphire-owl.sh
        container: qc.sty_sloppy-olivine-tarantula
  QC.Ver:
    repos:
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-service get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-lime-bandicoot.sh
        container: qc.ver_cozy-coral-serval
timeout: 5400
